/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFlowbiteArrowRightOutline: typeof import('~icons/flowbite/arrow-right-outline')['default']
    IHealthiconsInpatientOutline24px: typeof import('~icons/healthicons/inpatient-outline24px')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiSettings: typeof import('~icons/mdi/settings')['default']
    IMynauiArrowLongLeft: typeof import('~icons/mynaui/arrow-long-left')['default']
    ISolarUserOutline: typeof import('~icons/solar/user-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
