/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectPatient: typeof import('./src/components/patient/ConnectPatient.vue')['default']
    CriticalSettings: typeof import('./src/components/settings/CriticalSettings.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IAkarIconsInfo: typeof import('~icons/akar-icons/info')['default']
    IFlowbiteArrowRightOutline: typeof import('~icons/flowbite/arrow-right-outline')['default']
    IHealthiconsInpatientOutline24px: typeof import('~icons/healthicons/inpatient-outline24px')['default']
    ILetsIconsSearchLight: typeof import('~icons/lets-icons/search-light')['default']
    'ILineMd:loadingTwotoneLoop': typeof import('~icons/line-md/loading-twotone-loop')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IMdiLoading: typeof import('~icons/mdi/loading')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiSettings: typeof import('~icons/mdi/settings')['default']
    IMdiUpload: typeof import('~icons/mdi/upload')['default']
    'IMingcute:aiFill': typeof import('~icons/mingcute/ai-fill')['default']
    IMynauiArrowLongLeft: typeof import('~icons/mynaui/arrow-long-left')['default']
    ISolarArrowRightOutline: typeof import('~icons/solar/arrow-right-outline')['default']
    ISolarUserOutline: typeof import('~icons/solar/user-outline')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    MedicalInputs: typeof import('./src/components/add/MedicalInputs.vue')['default']
    Number: typeof import('./src/components/indicators/Number.vue')['default']
    PatientDetails: typeof import('./src/components/patient/PatientDetails.vue')['default']
    PatientHealthIndicators: typeof import('./src/components/patient/PatientHealthIndicators.vue')['default']
    PatientMainInfo: typeof import('./src/components/patient/PatientMainInfo.vue')['default']
    Percentage: typeof import('./src/components/indicators/Percentage.vue')['default']
    PersonalInputs: typeof import('./src/components/add/PersonalInputs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/components/auth/Signup.vue')['default']
    Timeline: typeof import('./src/components/indicators/Timeline.vue')['default']
  }
}
