/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CriticalSettings: typeof import('./src/components/settings/CriticalSettings.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HealthIndicators: typeof import('./src/components/patient/HealthIndicators.vue')['default']
    IAkarIconsInfo: typeof import('~icons/akar-icons/info')['default']
    IFlowbiteArrowRightOutline: typeof import('~icons/flowbite/arrow-right-outline')['default']
    IHealthiconsInpatientOutline24px: typeof import('~icons/healthicons/inpatient-outline24px')['default']
    ILetsIconsSearchLight: typeof import('~icons/lets-icons/search-light')['default']
    IMaterialSymbolsLightSearchRounded: typeof import('~icons/material-symbols-light/search-rounded')['default']
    IMdiAbout: typeof import('~icons/mdi/about')['default']
    IMdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    IMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IMdiBell: typeof import('~icons/mdi/bell')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiSettings: typeof import('~icons/mdi/settings')['default']
    IMynauiArrowLongLeft: typeof import('~icons/mynaui/arrow-long-left')['default']
    IMynauiSearch: typeof import('~icons/mynaui/search')['default']
    ISolarArrowRightOutline: typeof import('~icons/solar/arrow-right-outline')['default']
    ISolarUserOutline: typeof import('~icons/solar/user-outline')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavLink: typeof import('./src/components/layout/NavLink.vue')['default']
    Number: typeof import('./src/components/indicators/Number.vue')['default']
    PatientCard: typeof import('./src/components/PatientCard.vue')['default']
    PatientDetails: typeof import('./src/components/patient/PatientDetails.vue')['default']
    PatientHealthIndicators: typeof import('./src/components/patient/PatientHealthIndicators.vue')['default']
    PatientMainInfo: typeof import('./src/components/patient/PatientMainInfo.vue')['default']
    Percentage: typeof import('./src/components/indicators/Percentage.vue')['default']
    Ph: typeof import('./src/components/indicators/Ph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/indicators/Timeline.vue')['default']
  }
}
